name: Sync Fork
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: Sync Fork
        uses: repo-sync/github-sync@v2
        with:
          source_branch: "main"
          destination_branch: "tags-sync"
          source_repo: "sp-tarkov/build"
          sync_tags: "*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
